export const LANGUAGES = [
    { id: 1, name: "English", value: "English" },
    { id: 2, name: "Hindi", value: "Hindi" },
    { id: 3, name: "Tamil", value: "Tamil" },
    { id: 4, name: "Telugu", value: "Telugu" },
    { id: 5, name: "Kannada", value: "Kannada" },
    { id: 6, name: "Malayalam", value: "Malayalam" },
    { id: 7, name: "Marathi", value: "Marathi" },
    { id: 8, name: "Gujarati", value: "Gujarati" },
    { id: 9, name: "Punjabi", value: "Punjabi" },
    { id: 10, name: "Bengali", value: "Bengali" },
    { id: 11, name: "Odia", value: "Odia" },
    { id: 12, name: "Assamese", value: "Assamese" },
    { id: 13, name: "Sinhala", value: "Sinhala" },
    { id: 14, name: "Konkani", value: "Konkani" },
    { id: 15, name: "Nepali", value: "Nepali" },
    { id: 16, name: "Sanskrit", value: "Sanskrit" },
    { id: 17, name: "Urdu", value: "Urdu" },
    { id: 18, name: "Other", value: "Other" },
]